// ─────────────────────────────────────────────────────────────────────────────
// AppStrings — all translation key constants for Aula 360.
// Usage: AppStrings.welcomeBack  →  'welcome_back'
// Then pass to tr() helper:  ref.watchTr(AppStrings.welcomeBack)
// ─────────────────────────────────────────────────────────────────────────────

class AppStrings {
  // ===========================================================================
  // 1. FIXED APP UI STRINGS
  // ===========================================================================

  // ── App & Splash ──────────────────────────────────────────────────────────
  static const String appName = 'app_name';
  static const String appTagline = 'app_tagline';
  static const String appInitializing = 'app_initializing';

  // ── Language Selection ────────────────────────────────────────────────────
  static const String languageSelectTitle = 'language_select_title';
  static const String languageSelectSubtitle = 'language_select_subtitle';
  static const String languageEnglish = 'language_english';
  static const String languageSpanish = 'language_spanish';
  static const String languageContinue = 'language_continue';
  static const String selectLanguage = 'select_language';
  static const String languagePickerTitle = 'language_picker_title';
  static const String languageEnglishUs = 'language_english_us';
  static const String languageSpanishLabel = 'language_spanish_label';

  // ── Onboarding ────────────────────────────────────────────────────────────
  static const String onboardingSkip = 'onboarding_skip';
  static const String onboardingNext = 'onboarding_next';
  static const String onboardingContinue = 'onboarding_continue';
  static const String onboardingTitle1 = 'onboarding_title_1';
  static const String onboardingDesc1 = 'onboarding_desc_1';
  static const String onboardingTagUnifiedHub = 'onboarding_tag_unified_hub';
  static const String onboardingTagSmartTimetables = 'onboarding_tag_smart_timetables';
  static const String onboardingTagRealtimeSync = 'onboarding_tag_realtime_sync';
  static const String onboardingTitle2 = 'onboarding_title_2';
  static const String onboardingDesc2 = 'onboarding_desc_2';
  static const String onboardingTagLiveAttendance = 'onboarding_tag_live_attendance';
  static const String onboardingTagHomeworkTracker = 'onboarding_tag_homework_tracker';
  static const String onboardingTagProgressReports = 'onboarding_tag_progress_reports';
  static const String onboardingTagClassSchedules = 'onboarding_tag_class_schedules';
  static const String onboardingTitle3 = 'onboarding_title_3';
  static const String onboardingDesc3 = 'onboarding_desc_3';

  // ── Choose Role ───────────────────────────────────────────────────────────
  static const String roleSelectTitle = 'role_select_title';
  static const String roleSelectSubtitle = 'role_select_subtitle';
  static const String roleParentTitle = 'role_parent_title';
  static const String roleParentSubtitle = 'role_parent_subtitle';
  static const String roleParentDescription = 'role_parent_description';
  static const String roleTeacherTitle = 'role_teacher_title';
  static const String roleTeacherDescription = 'role_teacher_description';
  static const String roleContinueAsParent = 'role_continue_as_parent';
  static const String roleContinueAsTeacher = 'role_continue_as_teacher';
  static const String roleContinue = 'role_continue';

  // ── Navigation Tabs ───────────────────────────────────────────────────────
  static const String navHome = 'nav_home';
  static const String navClasses = 'nav_classes';
  static const String navStudents = 'nav_students';
  static const String navSchedule = 'nav_schedule';
  static const String navReports = 'nav_reports';
  static const String navNotifications = 'nav_notifications';
  static const String navProfile = 'nav_profile';

  // ── Authentication (Login / Signup) ───────────────────────────────────────
  static const String parentLoginTitle = 'parent_login_title';
  static const String teacherLoginTitle = 'teacher_login_title';
  static const String welcomeBack = 'welcome_back';
  static const String parentLoginSubtitle = 'parent_login_subtitle';
  static const String teacherLoginSubtitle = 'teacher_login_subtitle';
  static const String fieldMobileOrEmail = 'field_mobile_or_email';
  static const String fieldMobileOrEmailHint = 'field_mobile_or_email_hint';
  static const String fieldEmailOrFacultyId = 'field_email_or_faculty_id';
  static const String fieldEmailOrFacultyIdHint = 'field_email_or_faculty_id_hint';
  static const String fieldPassword = 'field_password';
  static const String fieldPasswordHint = 'field_password_hint';
  static const String rememberDevice = 'remember_device';
  static const String forgotPassword = 'forgot_password';
  static const String btnLoginAula360 = 'btn_login_aula360';
  static const String noAccountYet = 'no_account_yet';
  static const String createAccount = 'create_account';
  static const String loginAsTeacher = 'login_as_teacher';
  static const String loginAsParent = 'login_as_parent';
  static const String createAccountTitle = 'create_account_title';
  static const String createYourAccount = 'create_your_account';
  static const String parentSignupSubtitle = 'parent_signup_subtitle';
  static const String teacherRegistrationTitle = 'teacher_registration_title';
  static const String registerAsFaculty = 'register_as_faculty';
  static const String teacherSignupSubtitle = 'teacher_signup_subtitle';
  static const String fieldFullName = 'field_full_name';
  static const String fieldFullNameHint = 'field_full_name_hint';
  static const String fieldMobileNumber = 'field_mobile_number';
  static const String fieldMobileHint = 'field_mobile_hint';
  static const String fieldMobileNumberHint = 'field_mobile_hint';
  static const String fieldEmailAddress = 'field_email_address';
  static const String fieldEmailHint = 'field_email_hint';
  static const String fieldEmailAddressHint = 'field_email_hint';
  static const String fieldAcademyEmail = 'field_academy_email';
  static const String fieldAcademyEmailHint = 'field_academy_email_hint';
  static const String fieldPasswordCreateHint = 'field_password_create_hint';
  static const String passwordHintText = 'password_hint_text';
  static const String passwordReqNotice = 'password_hint_text';
  static const String btnCreateAccount = 'btn_create_account';
  static const String alreadyHaveAccount = 'already_have_account';
  static const String logIn = 'log_in';
  static const String btnLogIn = 'log_in';
  static const String agreeTermsPrefix = 'agree_terms_prefix';
  static const String termsAndConditions = 'terms_and_conditions';
  static const String termsAnd = 'terms_and';
  static const String privacyPolicy = 'privacy_policy';
  static const String teacherTermsRequired = 'teacher_terms_required';

  // ── Forgot & Reset Password ───────────────────────────────────────────────
  static const String forgotPasswordHeader = 'forgot_password_header';
  static const String forgotPasswordTitle = 'forgot_password_title';
  static const String forgotPasswordSubtitle = 'forgot_password_subtitle';
  static const String fieldEmailRegistered = 'field_email_registered';
  static const String fieldEmailRegisteredHint = 'field_email_registered_hint';
  static const String btnSendVerification = 'btn_send_verification';
  static const String resetParentPassword = 'reset_parent_password';
  static const String resetTeacherPassword = 'reset_teacher_password';
  static const String resetPasswordHeader = 'reset_password_header';
  static const String resetPasswordTitle = 'reset_password_title';
  static const String resetPasswordSubtitle = 'reset_password_subtitle';
  static const String fieldNewPassword = 'field_new_password';
  static const String fieldNewPasswordHint = 'field_new_password_hint';
  static const String fieldConfirmPassword = 'field_confirm_password';
  static const String fieldConfirmPasswordHint = 'field_confirm_password_hint';
  static const String btnResetPassword = 'btn_reset_password';
  static const String passwordMismatchTitle = 'password_mismatch_title';
  static const String passwordMismatchMessage = 'password_mismatch_message';
  static const String passwordResetSuccessTitle = 'password_reset_success_title';
  static const String passwordResetSuccessMessage = 'password_reset_success_message';
  static const String changePasswordTitle = 'change_password_title';
  static const String currentPassword = 'current_password';
  static const String currentPasswordHint = 'current_password_hint';
  static const String changePasswordHeaderSubtitle = 'change_password_header_subtitle';
  static const String invalidPassword = 'invalid_password';
  static const String passwordDifferentMsg = 'password_different_msg';
  static const String passwordUpdatedMsg = 'password_updated_msg';

  // ── OTP ───────────────────────────────────────────────────────────────────
  static const String otpHeader = 'otp_header';
  static const String otpVerifyAccount = 'otp_verify_account';
  static const String otpVerifyIdentity = 'otp_verify_identity';
  static const String otpSignupDesc = 'otp_signup_desc';
  static const String otpForgotDesc = 'otp_forgot_desc';
  static const String otpEnterCodeLabel = 'otp_enter_code_label';
  static const String otpExpiresPrefix = 'otp_expires_prefix';
  static const String otpResend = 'otp_resend';
  static const String otpSpamNote = 'otp_spam_note';
  static const String otpVerifyContinue = 'otp_verify_continue';
  static const String otpVerifyReset = 'otp_verify_reset';
  static const String otpRequiredTitle = 'otp_required_title';
  static const String otpRequiredMessage = 'otp_required_message';

  // ── Settings (Teacher & Parent) ───────────────────────────────────────────
  static const String settingsTitle = 'settings_title';
  static const String settingsProfileBreadcrumb = 'settings_profile_breadcrumb';
  static const String settingsSectionLanguage = 'settings_section_language';
  static const String settingsSectionNotifications = 'settings_section_notifications';
  static const String settingsSectionAccountSecurity = 'settings_section_account_security';
  static const String settingsSectionAccount = 'settings_section_account';
  static const String settingsLangDisplayLanguage = 'settings_lang_display_language';
  static const String settingsLangSubtitle = 'settings_lang_subtitle';
  static const String settingsLangLabel = 'settings_lang_label';
  static const String settingsNotifClassReminders = 'settings_notif_class_reminders';
  static const String settingsNotifClassRemindersSub = 'settings_notif_class_reminders_sub';
  static const String settingsNotifParentMessages = 'settings_notif_parent_messages';
  static const String settingsNotifParentMessagesSub = 'settings_notif_parent_messages_sub';
  static const String settingsNotifPostClass = 'settings_notif_post_class';
  static const String settingsNotifPostClassSub = 'settings_notif_post_class_sub';
  static const String settingsNotifPush = 'settings_notif_push';
  static const String settingsNotifPushSub = 'settings_notif_push_sub';
  static const String settingsNotifAttendanceAlerts = 'settings_notif_attendance_alerts';
  static const String settingsNotifAttendanceAlertsSub = 'settings_notif_attendance_alerts_sub';
  static const String settingsSecurityBiometric = 'settings_security_biometric';
  static const String settingsSecurityBiometricSub = 'settings_security_biometric_sub';
  static const String settingsSecurityChangePassword = 'settings_security_change_password';
  static const String settingsSecurityChangePasswordSub = 'settings_security_change_password_sub';
  static const String settingsSecurityActiveSessions = 'settings_security_active_sessions';
  static const String settingsSecurityActiveSessionsSub = 'settings_security_active_sessions_sub';
  static const String settingsSessionsTitle = 'settings_sessions_title';
  static const String settingsSessionsSubtitle = 'settings_sessions_subtitle';
  static const String settingsSessionsSignoutOthers = 'settings_sessions_signout_others';
  static const String settingsSessionsCurrent = 'settings_sessions_current';
  static const String settingsSessionsBadge = 'settings_sessions_badge';
  static const String settingsBiometricEnabled = 'settings_biometric_enabled';
  static const String settingsBiometricDisabled = 'settings_biometric_disabled';
  static const String settingsClassRemindersEnabled = 'settings_class_reminders_enabled';
  static const String settingsClassRemindersDisabled = 'settings_class_reminders_disabled';
  static const String settingsParentMessagesEnabled = 'settings_parent_messages_enabled';
  static const String settingsParentMessagesDisabled = 'settings_parent_messages_disabled';
  static const String settingsPostClassEnabled = 'settings_post_class_enabled';
  static const String settingsPostClassDisabled = 'settings_post_class_disabled';
  static const String settingsLangChanged = 'settings_lang_changed';
  static const String settingsSessionsSignedout = 'settings_sessions_signedout';

  // ── Add Child / Student Enrollment ────────────────────────────────────────
  static const String addChildTitle = 'add_child_title';
  static const String studentInfoTitle = 'student_info_title';
  static const String studentInfoDesc = 'student_info_desc';
  static const String newStudentEnrollment = 'new_student_enrollment';
  static const String parentAccount = 'parent_account';
  static const String verified = 'verified';
  static const String uploadPhotoOptional = 'upload_photo_optional';
  static const String uploadPhotoHint = 'upload_photo_hint';
  static const String dateOfBirth = 'date_of_birth';
  static const String gradeLevel = 'grade_level';
  static const String gender = 'gender';
  static const String genderFemale = 'gender_female';
  static const String genderMale = 'gender_male';
  static const String genderPreferNot = 'gender_prefer_not';
  static const String studentId = 'student_id';
  static const String providedByAcademy = 'provided_by_academy';
  static const String studentConnectionNotice = 'student_connection_notice';
  static const String assignedAfterEnrollment = 'assigned_after_enrollment';
  static const String saveChild = 'save_child';
  static const String cancel = 'cancel';
  static const String myChildren = 'my_children';
  static const String addAnotherChild = 'add_another_child';
  static const String active = 'active';
  static const String attendance = 'attendance';
  static const String childProfile = 'child_profile';
  static const String academicActivity = 'academic_activity';

  // ── Profile Setup & Management ────────────────────────────────────────────
  static const String profileSetupTitle = 'profile_setup_title';
  static const String editProfileTitle = 'edit_profile_title';
  static const String editProfileDesc = 'edit_profile_desc';
  static const String parentContactDetails = 'parent_contact_details';
  static const String parentPortal = 'parent_portal';
  static const String completeYourProfile = 'complete_your_profile';
  static const String completeYourProfileDesc = 'complete_your_profile_desc';
  static const String chooseProfilePhoto = 'choose_profile_photo';
  static const String selectOptionProfilePhoto = 'select_option_profile_photo';
  static const String chooseFromGallery = 'choose_from_gallery';
  static const String takeAPhoto = 'take_a_photo';
  static const String removePhoto = 'remove_photo';
  static const String parentFullName = 'parent_full_name';
  static const String enterYourFullName = 'enter_your_full_name';
  static const String primaryMobileNumber = 'primary_mobile_number';
  static const String enterMobileNumber = 'enter_mobile_number';
  static const String relationshipToStudent = 'relationship_to_student';
  static const String selectRelationship = 'select_relationship';
  static const String residentialAddress = 'residential_address';
  static const String fieldResidentialAddress = 'residential_address';
  static const String residentialAddressHint = 'residential_address_hint';
  static const String btnCompleteProfile = 'btn_complete_profile';
  static const String btnSaveChanges = 'btn_save_changes';
  static const String navigatesToParentDashboard = 'navigates_to_parent_dashboard';
  static const String relationshipMother = 'relationship_mother';
  static const String relationshipFather = 'relationship_father';
  static const String relationshipGuardian = 'relationship_guardian';
  static const String profileCompletedSuccess = 'profile_completed_success';
  static const String profileCompletedTitle = 'profile_completed_title';
  static const String teacherProfileSetupTitle = 'teacher_profile_setup_title';
  static const String facultyProfileTitle = 'faculty_profile_title';
  static const String facultyProfileDesc = 'faculty_profile_desc';
  static const String academicIdentity = 'academic_identity';
  static const String fullLegalName = 'full_legal_name';
  static const String titleDepartment = 'title_department';
  static const String titleDepartmentHint = 'title_department_hint';
  static const String subjectsDisciplines = 'subjects_disciplines';
  static const String addSubject = 'add_subject';
  static const String addSubjectTitle = 'add_subject_title';
  static const String selectSubjectSubtitle = 'select_subject_subtitle';
  static const String campusOfficeDetails = 'campus_office_details';
  static const String assignedCampusBuilding = 'assigned_campus_building';
  static const String roomHall = 'room_hall';
  static const String roomHallHint = 'room_hall_hint';
  static const String officeContact = 'office_contact';
  static const String facultyBioFocus = 'faculty_bio_focus';
  static const String facultyBioHint = 'faculty_bio_hint';
  static const String optional = 'optional';
  static const String btnCompleteTeacherSetup = 'btn_complete_teacher_setup';
  static const String navigatesToFacultyDashboard = 'navigates_to_faculty_dashboard';
  static const String logout = 'logout';
  static const String logoutConfirmTitle = 'logout_confirm_title';
  static const String logoutConfirmMessage = 'logout_confirm_message';
  static const String today = 'today';
  static const String upcomingClasses = 'upcoming_classes';
  static const String academyAndFamily = 'academy_and_family';
  static const String academicYearLabel = 'academic_year_label';
  static const String communicationTitle = 'communication_title';
  static const String communicationSubtitle = 'communication_subtitle';
  static const String paymentsTitle = 'payments_title';
  static const String paymentsSubtitle = 'payments_subtitle';
  static const String upToDate = 'up_to_date';
  static const String settingsMenuSubtitle = 'settings_menu_subtitle';
  static const String emailNotificationNotice = 'email_notification_notice';
  static const String phoneUrgentNotice = 'phone_urgent_notice';
  static const String profileUpdatedSuccess = 'profile_updated_success';

  // ── Class Details & Teacher Info (Fixed UI) ──────────────────────────────
  static const String classDetailsTitle = 'class_details_title';
  static const String scheduleAndTiming = 'schedule_and_timing';
  static const String date = 'date';
  static const String timeSlot = 'time_slot';
  static const String academyLocation = 'academy_location';
  static const String teacherInfoTitle = 'teacher_info_title';
  static const String viewFloorPlan = 'view_floor_plan';
  static const String directCommunication = 'direct_communication';
  static const String portalDirectMessage = 'portal_direct_message';
  static const String officeHoursTitle = 'office_hours_title';
  static const String emailAddressTitle = 'email_address_title';
  static const String sendMessageBtn = 'send_message_btn';
  static const String requestOfficeHourBtn = 'request_office_hour_btn';
  static const String sendEmailBtn = 'send_email_btn';
  static const String viewFullSchedule = 'view_full_schedule';
  static const String weekPrefix = 'week_prefix';
  static const String teacherOfPrefix = 'teacher_of_prefix';
  static const String remainingToday = 'remaining_today';
  static const String completedEarlier = 'completed_earlier';
  static const String tomorrow = 'tomorrow';
  static const String classReportAction = 'class_report_action';
  static const String completedPresent = 'completed_present';

  // ── Reports & Homework (Fixed UI) ────────────────────────────────────────
  static const String reportDetailTitle = 'report_detail_title';
  static const String allReports = 'all_reports';
  static const String present = 'present';
  static const String late = 'late';
  static const String absent = 'absent';
  static const String excused = 'excused';
  static const String teacherNote = 'teacher_note';
  static const String viewReport = 'view_report';
  static const String noReportsFound = 'no_reports_found';
  static const String noReportsForCategory = 'no_reports_for_category';
  static const String homeworkAndTasks = 'homework_and_tasks';
  static const String viewHomework = 'view_homework';
  static const String teacherObservation = 'teacher_observation';
  static const String showLess = 'show_less';
  static const String readFullNote = 'read_full_note';
  static const String status = 'status';
  static const String duration = 'duration';
  static const String participation = 'participation';
  static const String downloadReport = 'download_report';
  static const String homeworkTitle = 'homework_title';
  static const String allTab = 'all_tab';
  static const String pendingTab = 'pending_tab';
  static const String completedTab = 'completed_tab';
  static const String viewDetails = 'view_details';
  static const String homeworkDetailsTitle = 'homework_details_title';
  static const String instructionsTitle = 'instructions_title';
  static const String attachmentsTitle = 'attachments_title';
  static const String submissionStatusTitle = 'submission_status_title';
  static const String submissionPending = 'submission_pending';

  // ── Attendance (Fixed UI) ────────────────────────────────────────────────
  static const String currentQuarter = 'current_quarter';
  static const String sessionsCount = 'sessions_count';

  // ── Notifications (Fixed UI) ─────────────────────────────────────────────
  static const String academyUpdates = 'academy_updates';
  static const String stayUpdatedSubtitle = 'stay_updated_subtitle';
  static const String unreadBadge = 'unread_badge';
  static const String allCaughtUp = 'all_caught_up';

  // ── Payment & Invoicing (Fixed UI) ────────────────────────────────────────
  static const String tuitionPaymentTitle = 'tuition_payment_title';
  static const String paymentMethodTitle = 'payment_method_title';
  static const String processedByStripe = 'processed_by_stripe';
  static const String totalToPay = 'total_to_pay';
  static const String cardNumber = 'card_number';
  static const String expiration = 'expiration';
  static const String cvc = 'cvc';
  static const String country = 'country';
  static const String postalCode = 'postal_code';
  static const String saveCardFuture = 'save_card_future';
  static const String autoBillingSubtitle = 'auto_billing_subtitle';
  static const String payNowBtn = 'pay_now_btn';
  static const String paymentSuccessTitle = 'payment_success_title';
  static const String paymentSuccessSubtitle = 'payment_success_subtitle';
  static const String paidAndSettled = 'paid_and_settled';
  static const String paymentReceiptTitle = 'payment_receipt_title';
  static const String downloadReceiptPdf = 'download_receipt_pdf';
  static const String receiptEmailSentNotice = 'receipt_email_sent_notice';
  static const String finishBtn = 'finish_btn';
  static const String periodLabel = 'period_label';
  static const String studentLabel = 'student_label';
  static const String invoiceLabel = 'invoice_label';
  static const String methodLabel = 'method_label';

  // ── Chat & Communication (Fixed UI) ──────────────────────────────────────
  static const String chatTutoringTab = 'chat_tutoring_tab';
  static const String chatAdministrationTab = 'chat_administration_tab';
  static const String typeMessageHint = 'type_message_hint';

  // ── Teacher Features (Fixed UI) ──────────────────────────────────────────
  static const String assignedClassesTitle = 'assigned_classes_title';
  static const String studentsCount = 'students_count';
  static const String dateTime = 'date_time';
  static const String classroom = 'classroom';
  static const String enrollment = 'enrollment';
  static const String sessionInfoTitle = 'session_info_title';
  static const String todaysTopic = 'todays_topic';
  static const String roomStatusTitle = 'room_status_title';
  static const String startClassAndAttendance = 'start_class_and_attendance';
  static const String takeAttendance = 'take_attendance';
  static const String finishAttendance = 'finish_attendance';
  static const String presentCountLabel = 'present_count_label';
  static const String markAllPresent = 'mark_all_present';
  static const String allStudentsMarkedPresent = 'all_students_marked_present';
  static const String attendanceCompletedTitle = 'attendance_completed_title';
  static const String endClassTitle = 'end_class_title';
  static const String endClassSessionTitle = 'end_class_session_title';
  static const String endClassSessionDesc = 'end_class_session_desc';
  static const String subjectAndGroupTitle = 'subject_and_group_title';
  static const String location = 'location';
  static const String scheduleTitle = 'schedule_title';
  static const String attendanceSummaryTitle = 'attendance_summary_title';
  static const String finishClassAndCreateReport = 'finish_class_and_create_report';
  static const String backToAttendance = 'back_to_attendance';
  static const String attendanceLockedNotice = 'attendance_locked_notice';
  static const String postClassReportTitle = 'post_class_report_title';
  static const String contentDeliveredTitle = 'content_delivered_title';
  static const String assignedTasksTitle = 'assigned_tasks_title';
  static const String conductAndAttitudeTitle = 'conduct_and_attitude_title';
  static const String effortAndDedicationTitle = 'effort_and_dedication_title';
  static const String quickNotesTitle = 'quick_notes_title';
  static const String sendReportBtn = 'send_report_btn';
  static const String conductNeedsAttention = 'conduct_needs_attention';
  static const String conductSatisfactory = 'conduct_satisfactory';
  static const String conductExcellent = 'conduct_excellent';
  static const String effortModerate = 'effort_moderate';
  static const String effortAdequate = 'effort_adequate';
  static const String effortHighPerformance = 'effort_high_performance';
  static const String reportSubmittedTitle = 'report_submitted_title';
  static const String reportSubmittedSubtitle = 'report_submitted_subtitle';
  static const String recordedSessionsTitle = 'recorded_sessions_title';
  static const String recordedSessionsSubtitle = 'recorded_sessions_subtitle';
  static const String inTotal = 'in_total';
  static const String myStudentsTitle = 'my_students_title';
  static const String searchStudentHint = 'search_student_hint';
  static const String rosterAssignedTitle = 'roster_assigned_title';
  static const String studentDetailsTitle = 'student_details_title';
  static const String latestClassReportTitle = 'latest_class_report_title';
  static const String activeHomeworkTitle = 'active_homework_title';
  static const String facultyNoteTitle = 'faculty_note_title';
  static const String metricAttendances = 'metric_attendances';
  static const String metricPerformance = 'metric_performance';
  static const String metricHomework = 'metric_homework';
  static const String reviewPending = 'review_pending';
  static const String addNoteBtn = 'add_note_btn';
  static const String addNoteTitle = 'add_note_title';
  static const String addNoteHint = 'add_note_hint';
  static const String saveNoteBtn = 'save_note_btn';
  static const String academyNavigationTitle = 'academy_navigation_title';
  static const String teacherPortalBadge = 'teacher_portal_badge';
  static const String teacherIdBadge = 'teacher_id_badge';
  static const String academyMessagesTitle = 'academy_messages_title';
  static const String academyMessagesSubtitle = 'academy_messages_subtitle';
  static const String announcementsTitle = 'announcements_title';
  static const String announcementsSubtitle = 'announcements_subtitle';
  static const String familyCommunicationTitle = 'family_communication_title';
  static const String familyCommunicationSubtitle = 'family_communication_subtitle';
  static const String nextClass = 'next_class';
  static const String scheduled = 'scheduled';
  static const String groupA = 'group_a';
  static const String groupB = 'group_b';
  static const String oneOnOne = 'one_on_one';
  static const String filed = 'filed';
  static const String submitted = 'submitted';
  static const String needsCheckIn = 'needs_check_in';
  static const String attendanceRecordTitle = 'attendance_record_title';
  static const String attendanceAndParticipationTitle = 'attendance_and_participation_title';
  static const String facultyObservationTitle = 'faculty_observation_title';
  static const String downloadOfficialRecordPdf = 'download_official_record_pdf';
  static const String facultyPrefix = 'faculty_prefix';
  static const String activeStatus = 'active_status';
  static const String deskPrefix = 'desk_prefix';
  static const String jpgPngMax5mb = 'jpg_png_max_5mb';
  static const String imageSizeLimitError = 'image_size_limit_error';
  static const String imageSelectError = 'image_select_error';
  static const String personalContactInfoSubtitle = 'personal_contact_info_subtitle';
  static const String academyAnnouncementsSubtitle = 'academy_announcements_subtitle';
  static const String settingsNavSubtitle = 'settings_nav_subtitle';
  static const String facultyInfoTitle = 'faculty_info_title';
  static const String deptSubjectLabel = 'dept_subject_label';
  static const String officeRoomLabel = 'office_room_label';
  static const String briefBioNotes = 'brief_bio_notes';
  static const String preferredLanguage = 'preferred_language';
  static const String writeNoteHint = 'write_note_hint';
  static const String fieldIsRequiredSuffix = 'field_is_required_suffix';

  // ── Form Validation ───────────────────────────────────────────────────────
  static const String emailRequired = 'email_required';
  static const String validEmailAddress = 'valid_email_address';
  static const String passwordRequired = 'password_required';
  static const String passwordMin8 = 'password_min_8';
  static const String uppercaseRequired = 'uppercase_required';
  static const String numberRequired = 'number_required';
  static const String confirmPasswordRequired = 'confirm_password_required';
  static const String enterPasswordFirst = 'enter_password_first';
  static const String passwordsDoNotMatch = 'passwords_do_not_match';
  static const String otpRequired = 'otp_required';
  static const String otpMustBe6Digits = 'otp_must_be_6_digits';
  static const String otpNumbersOnly = 'otp_numbers_only';
  static const String fieldRequired = 'field_required';
  static const String websiteUrlRequired = 'website_url_required';
  static const String validWebsiteUrl = 'valid_website_url';
  static const String nameRequired = 'name_required';
  static const String validName = 'valid_name';
  static const String phoneNumberRequired = 'phone_number_required';
  static const String validPhoneNumber = 'valid_phone_number';
  static const String usernameRequired = 'username_required';
  static const String usernameInvalidLength = 'username_invalid_length';
  static const String valueRequired = 'value_required';
  static const String validNumber = 'valid_number';
  static const String addressRequired = 'address_required';
  static const String validAddress = 'valid_address';
  static const String cityRequired = 'city_required';
  static const String validCityName = 'valid_city_name';
  static const String zipcodeRequired = 'zipcode_required';
  static const String validZipcode = 'valid_zipcode';
  static const String countryRequired = 'country_required';
  static const String validCountryName = 'valid_country_name';
  static const String descriptionRequired = 'description_required';
  static const String postalCodeRequired = 'postal_code_required';
  static const String validPostalCode = 'valid_postal_code';
  static const String dateOfBirthRequired = 'date_of_birth_required';
  static const String validDateOfBirth = 'valid_date_of_birth';
  static const String invalidDateFormat = 'invalid_date_format';
  static const String dateOfBirthFuture = 'date_of_birth_future';
  static const String invalidDateOfBirth = 'invalid_date_of_birth';
  static const String genderRequired = 'gender_required';
  static const String validGender = 'valid_gender';

  // ── Network / Launchers / Common UI ───────────────────────────────────────
  static const String dialerNotSupported = 'dialer_not_supported';
  static const String couldNotLaunchDialer = 'could_not_launch_dialer';
  static const String whatsappCannotBeOpened = 'whatsapp_cannot_be_opened';
  static const String couldNotLaunchWhatsapp = 'could_not_launch_whatsapp';
  static const String noInternetConnection = 'no_internet_connection';
  static const String back = 'back';
  static const String seeLess = 'see_less';
  static const String seeMore = 'see_more';
  static const String somethingWentWrong = 'something_went_wrong';
  static const String unknownErrorMessage = 'unknown_error_message';
  static const String tryAgain = 'try_again';
  static const String retry = 'retry';
  static const String somethingWentWrongRetry = 'something_went_wrong_retry';
  static const String noItemsFound = 'no_items_found';
  static const String listCurrentlyEmpty = 'list_currently_empty';
  static const String offlineMessage = 'offline_message';
  static const String unableToPlayVideo = 'unable_to_play_video';
  static const String videoUnavailableOrConnectionFailed = 'video_unavailable_or_connection_failed';

  // ── Greetings ─────────────────────────────────────────────────────────────
  static const String goodMorning = 'good_morning';
  static const String goodAfternoon = 'good_afternoon';
  static const String goodEvening = 'good_evening';
  static const String goodNight = 'good_night';

  // ===========================================================================
  // 2. SAMPLE / STATIC MOCK DATA STRINGS (Removable / replaceable later)
  // ===========================================================================

  // ── Spanish Academic Terms & Rooms ────────────────────────────────────────
  static const String aula1 = 'aula_1';
  static const String aula2 = 'aula_2';
  static const String aula3 = 'aula_3';
  static const String aula4 = 'aula_4';
  static const String aulaMagna = 'aula_magna';
  static const String lab1 = 'lab_1';
  static const String lab2 = 'lab_2';

  // ── Spanish Academic Levels ───────────────────────────────────────────────
  static const String primaria1 = 'primaria_1';
  static const String primaria2 = 'primaria_2';
  static const String primaria3 = 'primaria_3';
  static const String primaria4 = 'primaria_4';
  static const String primaria5 = 'primaria_5';
  static const String primaria6 = 'primaria_6';
  static const String eso1 = 'eso_1';
  static const String eso2 = 'eso_2';
  static const String eso3 = 'eso_3';
  static const String eso4 = 'eso_4';
  static const String bachillerato1 = 'bachillerato_1';
  static const String bachillerato2 = 'bachillerato_2';

  // ── Spanish Academic Subjects ─────────────────────────────────────────────
  static const String subjectMath = 'subject_math';
  static const String subjectPhysicsChemistry = 'subject_physics_chemistry';
  static const String subjectSpanishLanguage = 'subject_spanish_language';
  static const String subjectEnglish = 'subject_english';
  static const String subjectBiology = 'subject_biology';
  static const String subjectHistory = 'subject_history';
  static const String subjectStatistics = 'subject_statistics';
  static const String subjectAlgebra = 'subject_algebra';

  // ── Home & Schedule Mock Labels ───────────────────────────────────────────
  static const String homeGreeting = 'home_greeting';
  static const String homeSchedule = 'home_schedule';
  static const String homeInPerson = 'home_in_person';
  static const String homeToday = 'home_today';
  static const String homeClassesScheduled = 'home_classes_scheduled';
  static const String homeNextLabel = 'home_next_label';
  static const String homeAttendanceLabel = 'home_attendance_label';
  static const String homePresentToday = 'home_present_today';
  static const String homeAttendanceHistory = 'home_attendance_history';
  static const String homeTodaysSchedule = 'home_todays_schedule';
  static const String homeViewAll = 'home_view_all';
  static const String homeSwitch = 'home_switch';
  static const String homeDetails = 'home_details';
  static const String homeCampusOpen = 'home_campus_open';
  static const String homeNextUp = 'home_next_up';
  static const String homeStarts = 'home_starts';

  // ── Class Details & Teacher Info Mock Data ────────────────────────────────
  static const String mockMainBuilding = 'mock_main_building';
  static const String mockBuildingFloor = 'mock_building_floor';
  static const String mockFloorPlanOf = 'mock_floor_plan_of';
  static const String mockTeacherOf = 'mock_teacher_of';
  static const String mockOfficeHours = 'mock_office_hours';
  static const String mockPhysicsDesc = 'mock_physics_desc';
  static const String mockLanguageDesc = 'mock_language_desc';
  static const String mockMathDesc = 'mock_math_desc';
  static const String mockTeacherBio = 'mock_teacher_bio';
  static const String mockTeacherDept = 'mock_teacher_dept';
  static const String mockTeacherAcademyId = 'mock_teacher_academy_id';
  static const String mockMessagePrompt = 'mock_message_prompt';
  static const String mockOfficeHoursNotice = 'mock_office_hours_notice';
}
